# -*- coding: utf-8 -*-
"""consolidação planilha e previsão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEfXmJ6nGxjPD4p07B4DhsyXL1xZBtMk
"""

import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from google.colab import files

#Considerando avaliação de colaboradores com previsão de alocação acima de 100 horas e abaixo de 30 horas

#upload da planilha consolidada
print("Envie a planilha consolidada (.xlsx)")
uploaded = files.upload()
arquivo = list(uploaded.keys())[0]

#ler planilha
df = pd.read_excel(arquivo)

#Selecionar apenas colunas de meses
mes_cols = [c for c in df.columns if "-" in str(c)]
dados = df[['Matrícula', 'Colaborador'] + mes_cols]

# converter para formato "long"
dados_long = dados.melt(id_vars=['Matrícula', 'Colaborador'],
                        var_name='Mes', value_name='Horas')
dados_long['Mes'] = pd.to_datetime(dados_long['Mes'], format='%Y-%m')

#ordenar
dados_long = dados_long.sort_values(['Colaborador', 'Mes'])

#criar features de tendência
dados_long['Horas_Lag1'] = dados_long.groupby('Colaborador')['Horas'].shift(1)
dados_long['Horas_Lag2'] = dados_long.groupby('Colaborador')['Horas'].shift(2)
dados_long['Horas_Lag3'] = dados_long.groupby('Colaborador')['Horas'].shift(3)

#remover linhas sem histórico suficiente
dados_modelo = dados_long.dropna()

#separar dados para treino
X = dados_modelo[['Horas_Lag1', 'Horas_Lag2', 'Horas_Lag3']]
y = dados_modelo['Horas']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# treinar modelo
modelo = RandomForestRegressor(n_estimators=200, random_state=42)
modelo.fit(X_train.values, y_train) # Convert X_train to numpy array

# avaliar ===
pred_test = modelo.predict(X_test.values) # Convert X_test to numpy array
print("Erro médio absoluto:", mean_absolute_error(y_test, pred_test))

#prever próximos 3 meses
resultados = []

for colaborador in dados['Colaborador'].unique():
    temp = dados_long[dados_long['Colaborador'] == colaborador].copy().sort_values('Mes')
    ultimos = temp.tail(3)['Horas'].tolist()

    if len(ultimos) == 3:
        for i in range(3):
            # Convert ultimos[-3:] to a numpy array and reshape for single sample prediction
            pred = modelo.predict(np.array(ultimos[-3:]).reshape(1, -1))[0]
            ultimos.append(pred)
            resultados.append({
                'Colaborador': colaborador,
                f'Previsao_M{i+1}': pred
            })

# consolidar resultados
pred_df = pd.DataFrame(resultados)
pred_medias = pred_df.groupby('Colaborador').mean().reset_index()

#classificar riscos
pred_medias['Risco_Excesso'] = pred_medias.mean(axis=1, numeric_only=True) > 100
pred_medias['Risco_Baixo'] = pred_medias.mean(axis=1, numeric_only=True) < 30

# salvar resultados
arquivo_saida = "Previsoes_Professores.xlsx"
pred_medias.to_excel(arquivo_saida, index=False)

print("Previsão concluída!")
files.download(arquivo_saida)

import pandas as pd
# from tkinter import Tk, filedialog # Removed as it's not compatible with Colab's environment
import os
from google.colab import files # Import Colab's file upload utility

# selecionar arquivo
uploaded = files.upload()

if not uploaded: # Check if any file was uploaded
    print("Nenhum arquivo selecionado. Encerrando.")
    exit()

#get the name of the first uploaded file
arquivo = list(uploaded.keys())[0]

#ler planilha
df = pd.read_excel(arquivo)

# garantir formato da data ===
df['Data atividade'] = pd.to_datetime(df['Data atividade'])

#criar coluna "Mês/Ano"
df['Mes_Ano'] = df['Data atividade'].dt.to_period('M')

#calcular total de horas (diurna + noturna)
df['Total_Horas'] = df['Carga Horária diurna'] + df['Carga Horária Noturna']

#agrupar dados por colaborador e mês
agrupado = (
    df.groupby(['Matrícula', 'Colaborador', 'Mes_Ano'], as_index=False)
    .agg(
        Total_Atividades=('Data atividade', 'count'),
        Total_Horas=('Total_Horas', 'sum')
    )
)

#transformar em formato de tabela dinâmica
tabela_pivot = agrupado.pivot_table(
    index=['Matrícula', 'Colaborador'],
    columns='Mes_Ano',
    values='Total_Horas',
    aggfunc='sum',
    fill_value=0
)

# calcular totais
tabela_pivot['Total_Horas'] = tabela_pivot.sum(axis=1)

# adicionar total de atividades por colaborador
total_atividades = (
    agrupado.groupby(['Matrícula', 'Colaborador'])['Total_Atividades']
    .sum()
    .rename('Total_Atividades')
)
tabela_final = tabela_pivot.merge(total_atividades, on=['Matrícula', 'Colaborador'])

# reorganizar colunas
cols = ['Total_Atividades'] + [c for c in tabela_pivot.columns if c != 'Total_Horas'] + ['Total_Horas']
tabela_final = tabela_final[cols]

#baixar arquivo Excel ===
nome_saida = os.path.splitext(arquivo)[0] + "_Consolidado_por_Colaborador.xlsx"
tabela_final.to_excel(nome_saida)

print(f"consolidação concluída!\nArquivo salvo em:\n{nome_saida}")
files.download(nome_saida)

import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from google.colab import files

#Considerando avaliação de colaboradores com previsão de alocação acima de 100 horas e abaixo de 30 horas

#upload da planilha consolidada
print("Envie a planilha consolidada (.xlsx)")
uploaded = files.upload()
arquivo = list(uploaded.keys())[0]

#ler planilha
df = pd.read_excel(arquivo)

#Selecionar apenas colunas de meses
mes_cols = [c for c in df.columns if "-" in str(c)]
dados = df[['Matrícula', 'Colaborador'] + mes_cols]

# converter para formato "long"
dados_long = dados.melt(id_vars=['Matrícula', 'Colaborador'],
                        var_name='Mes', value_name='Horas')
dados_long['Mes'] = pd.to_datetime(dados_long['Mes'], format='%Y-%m')

#ordenar
dados_long = dados_long.sort_values(['Colaborador', 'Mes'])

#criar features de tendência
dados_long['Horas_Lag1'] = dados_long.groupby('Colaborador')['Horas'].shift(1)
dados_long['Horas_Lag2'] = dados_long.groupby('Colaborador')['Horas'].shift(2)
dados_long['Horas_Lag3'] = dados_long.groupby('Colaborador')['Horas'].shift(3)

#remover linhas sem histórico suficiente
dados_modelo = dados_long.dropna()

#separar dados para treino
X = dados_modelo[['Horas_Lag1', 'Horas_Lag2', 'Horas_Lag3']]
y = dados_modelo['Horas']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# treinar modelo
modelo = RandomForestRegressor(n_estimators=200, random_state=42)
modelo.fit(X_train.values, y_train) # Convert X_train to numpy array

# avaliar ===
pred_test = modelo.predict(X_test.values) # Convert X_test to numpy array
print("Erro médio absoluto:", mean_absolute_error(y_test, pred_test))

#prever próximos 3 meses
resultados = []

for colaborador in dados['Colaborador'].unique():
    temp = dados_long[dados_long['Colaborador'] == colaborador].copy().sort_values('Mes')
    ultimos = temp.tail(3)['Horas'].tolist()

    if len(ultimos) == 3:
        for i in range(3):
            # Convert ultimos[-3:] to a numpy array and reshape for single sample prediction
            pred = modelo.predict(np.array(ultimos[-3:]).reshape(1, -1))[0]
            ultimos.append(pred)
            resultados.append({
                'Colaborador': colaborador,
                f'Previsao_M{i+1}': pred
            })

# consolidar resultados
pred_df = pd.DataFrame(resultados)
pred_medias = pred_df.groupby('Colaborador').mean().reset_index()

#classificar riscos
pred_medias['Risco_Excesso'] = pred_medias.mean(axis=1, numeric_only=True) > 100
pred_medias['Risco_Baixo'] = pred_medias.mean(axis=1, numeric_only=True) < 30

# salvar resultados
arquivo_saida = "Previsoes_Professores.xlsx"
pred_medias.to_excel(arquivo_saida, index=False)

print("Previsão concluída!")
files.download(arquivo_saida)

import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from google.colab import files

#Considerando avaliação de colaboradores com previsão de alocação acima de 100 horas e abaixo de 30 horas

#upload da planilha consolidada
print("Envie a planilha consolidada (.xlsx)")
uploaded = files.upload()
arquivo = list(uploaded.keys())[0]

#ler planilha
df = pd.read_excel(arquivo)

#Selecionar apenas colunas de meses
mes_cols = [c for c in df.columns if "-" in str(c)]
dados = df[['Matrícula', 'Colaborador'] + mes_cols]

# converter para formato "long"
dados_long = dados.melt(id_vars=['Matrícula', 'Colaborador'],
                        var_name='Mes', value_name='Horas')
dados_long['Mes'] = pd.to_datetime(dados_long['Mes'], format='%Y-%m')

#ordenar
dados_long = dados_long.sort_values(['Colaborador', 'Mes'])

#criar features de tendência
dados_long['Horas_Lag1'] = dados_long.groupby('Colaborador')['Horas'].shift(1)
dados_long['Horas_Lag2'] = dados_long.groupby('Colaborador')['Horas'].shift(2)
dados_long['Horas_Lag3'] = dados_long.groupby('Colaborador')['Horas'].shift(3)

#remover linhas sem histórico suficiente
dados_modelo = dados_long.dropna()

#separar dados para treino
X = dados_modelo[['Horas_Lag1', 'Horas_Lag2', 'Horas_Lag3']]
y = dados_modelo['Horas']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# treinar modelo
modelo = RandomForestRegressor(n_estimators=200, random_state=42)
modelo.fit(X_train.values, y_train) # Convert X_train to numpy array

# avaliar ===
pred_test = modelo.predict(X_test.values) # Convert X_test to numpy array
print("Erro médio absoluto:", mean_absolute_error(y_test, pred_test))

#prever próximos 3 meses
resultados = []

for colaborador in dados['Colaborador'].unique():
    temp = dados_long[dados_long['Colaborador'] == colaborador].copy().sort_values('Mes')
    ultimos = temp.tail(3)['Horas'].tolist()

    if len(ultimos) == 3:
        for i in range(3):
            # Convert ultimos[-3:] to a numpy array and reshape for single sample prediction
            pred = modelo.predict(np.array(ultimos[-3:]).reshape(1, -1))[0]
            ultimos.append(pred)
            resultados.append({
                'Colaborador': colaborador,
                f'Previsao_M{i+1}': pred
            })

# consolidar resultados
pred_df = pd.DataFrame(resultados)
pred_medias = pred_df.groupby('Colaborador').mean().reset_index()

#classificar riscos
pred_medias['Risco_Excesso'] = pred_medias.mean(axis=1, numeric_only=True) > 100
pred_medias['Risco_Baixo'] = pred_medias.mean(axis=1, numeric_only=True) < 30

# salvar resultados
arquivo_saida = "Previsoes_Professores.xlsx"
pred_medias.to_excel(arquivo_saida, index=False)

print("Previsão concluída!")
files.download(arquivo_saida)

import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from google.colab import files

#Considerando avaliação de colaboradores com previsão de alocação acima de 120 horas e abaixo de 10 horas

#upload da planilha consolidada
print("Envie a planilha consolidada (.xlsx)")
uploaded = files.upload()
arquivo = list(uploaded.keys())[0]

#ler planilha
df = pd.read_excel(arquivo)

#Selecionar apenas colunas de meses
mes_cols = [c for c in df.columns if "-" in str(c)]
dados = df[['Matrícula', 'Colaborador'] + mes_cols]

# converter para formato "long"
dados_long = dados.melt(id_vars=['Matrícula', 'Colaborador'],
                        var_name='Mes', value_name='Horas')
dados_long['Mes'] = pd.to_datetime(dados_long['Mes'], format='%Y-%m')

#ordenar
dados_long = dados_long.sort_values(['Colaborador', 'Mes'])

#criar features de tendência
dados_long['Horas_Lag1'] = dados_long.groupby('Colaborador')['Horas'].shift(1)
dados_long['Horas_Lag2'] = dados_long.groupby('Colaborador')['Horas'].shift(2)
dados_long['Horas_Lag3'] = dados_long.groupby('Colaborador')['Horas'].shift(3)

#remover linhas sem histórico suficiente
dados_modelo = dados_long.dropna()

#separar dados para treino
X = dados_modelo[['Horas_Lag1', 'Horas_Lag2', 'Horas_Lag3']]
y = dados_modelo['Horas']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# treinar modelo
modelo = RandomForestRegressor(n_estimators=200, random_state=42)
modelo.fit(X_train.values, y_train) # Convert X_train to numpy array

# avaliar ===
pred_test = modelo.predict(X_test.values) # Convert X_test to numpy array
print("Erro médio absoluto:", mean_absolute_error(y_test, pred_test))

#prever próximos 3 meses
resultados = []

for colaborador in dados['Colaborador'].unique():
    temp = dados_long[dados_long['Colaborador'] == colaborador].copy().sort_values('Mes')
    ultimos = temp.tail(3)['Horas'].tolist()

    if len(ultimos) == 3:
        for i in range(3):
            # Convert ultimos[-3:] to a numpy array and reshape for single sample prediction
            pred = modelo.predict(np.array(ultimos[-3:]).reshape(1, -1))[0]
            ultimos.append(pred)
            resultados.append({
                'Colaborador': colaborador,
                f'Previsao_M{i+1}': pred
            })

# consolidar resultados
pred_df = pd.DataFrame(resultados)
pred_medias = pred_df.groupby('Colaborador').mean().reset_index()

#classificar riscos
pred_medias['Risco_Excesso'] = pred_medias.mean(axis=1, numeric_only=True) > 120
pred_medias['Risco_Baixo'] = pred_medias.mean(axis=1, numeric_only=True) < 10

# salvar resultados
arquivo_saida = "Previsoes_Professores.xlsx"
pred_medias.to_excel(arquivo_saida, index=False)

print("Previsão concluída!")
files.download(arquivo_saida)



import matplotlib.pyplot as plt
import os
from google.colab import files
import shutil

# upload da planilha de previsões
print("Envie o arquivo 'Previsoes_Professores.xlsx'...")
uploaded = files.upload()
arquivo = list(uploaded.keys())[0]

# Ler a planilha
df = pd.read_excel(arquivo)
# A coluna 'Mes' não existe mais. As previsões estão em 'Previsao_M1', 'Previsao_M2', 'Previsao_M3'

#criar pasta para salvar os gráficos
os.makedirs("graficos_previsoes", exist_ok=True)

#gerar gráficos individuais por colaborador
prediction_cols = ['Previsao_M1', 'Previsao_M2', 'Previsao_M3']
month_labels = ['Mês Previsto 1', 'Mês Previsto 2', 'Mês Previsto 3']

for index, row in df.iterrows():
    colab = row['Colaborador']
    # Coletar as horas previstas para este colaborador
    horas_previstas = [row[col] for col in prediction_cols]

    plt.figure(figsize=(8,4))
    plt.plot(month_labels, horas_previstas, marker='o', color='orange', label='Previsto')

    # Linhas de referência
    plt.axhline(120, color='red', linestyle=':', label='Limite 120h')
    plt.axhline(10, color='green', linestyle=':', label='Subutilização')

    plt.title(f"Tendência de Horas Previstas - {colab}")
    plt.xlabel("Mês da Previsão")
    plt.ylabel("Horas Previstas")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    plt.savefig(f"graficos_previsoes/{colab}.png")
    plt.close()

print("📈 Gráficos individuais gerados.")

# Gráfico de barras - resumo de riscos
# Calcular a quantidade de professores em cada categoria de risco
num_excesso = df['Risco_Excesso'].sum() # True é contado como 1
num_baixo = df['Risco_Baixo'].sum() # True é contado como 1

# Criar um DataFrame para o resumo
resumo_riscos = pd.DataFrame({
    'Tipo de Risco': ['Risco_Excesso', 'Risco_Baixo'],
    'Quantidade': [num_excesso, num_baixo]
})

plt.figure(figsize=(6,4))
plt.bar(resumo_riscos['Tipo de Risco'], resumo_riscos['Quantidade'], color=['red', 'green'])
plt.title("📊 Resumo de Riscos - Professores")
plt.ylabel("Quantidade de Professores")
plt.grid(axis='y', linestyle=':', alpha=0.7)
plt.tight_layout()

plt.savefig("graficos_previsoes/Resumo_de_Riscos.png")
plt.close()

print("gráfico de barras de resumo gerado.")

# compactar e baixar
shutil.make_archive("graficos_previsoes", 'zip', "graficos_previsoes")
files.download("graficos_previsoes.zip")

print("Gráficos de resumo de riscos prontos para download.")